name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build1804:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install build env
      run: sudo apt-get install build-essential fakeroot devscripts haskell-debian-utils
    - name: Install build depends
      run: sudo apt install debhelper libglib2.0-dev libgtk-3-dev libusb-1.0-0-dev libtool-bin libtool libjpeg-dev cmake intltool libsane-dev
    - name: Build package
      run: debuild -i -us -uc -b

  build2004:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install build env
      run: sudo apt-get install build-essential fakeroot devscripts haskell-debian-utils
    - name: Install build depends
      run: sudo apt install debhelper libglib2.0-dev libgtk-3-dev libusb-1.0-0-dev libtool-bin libtool libjpeg-dev cmake intltool libsane-dev
    - name: Build package
      run: debuild -i -us -uc -b
